/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_database_sqlite_SQLiteGlobal */

#ifndef _Included_org_sqlite_database_sqlite_SQLiteGlobal
#define _Included_org_sqlite_database_sqlite_SQLiteGlobal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqlite_database_sqlite_SQLiteGlobal
 * Method:    nativeReleaseMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_database_sqlite_SQLiteGlobal_nativeReleaseMemory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
