/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_database_sqlite_SQLiteDebug */

#ifndef _Included_org_sqlite_database_sqlite_SQLiteDebug
#define _Included_org_sqlite_database_sqlite_SQLiteDebug
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sqlite_database_sqlite_SQLiteDebug_DEBUG_LOG_SLOW_QUERIES
#define org_sqlite_database_sqlite_SQLiteDebug_DEBUG_LOG_SLOW_QUERIES 0L
/*
 * Class:     org_sqlite_database_sqlite_SQLiteDebug
 * Method:    nativeGetPagerStats
 * Signature: (Lorg/sqlite/database/sqlite/SQLiteDebug/PagerStats;)V
 */
JNIEXPORT void JNICALL Java_org_sqlite_database_sqlite_SQLiteDebug_nativeGetPagerStats
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
